name: Project

include:
  - .configs/project.yml
  - Previews/previews.yml

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  MyTarget:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
        - path: iOS
    dependencies:
      - package: app-package
        product: AppFeature
    preBuildScripts:
      - name: Generate resources boilerplate
        script: "\"$SRCROOT/Scripts/generate_resources.sh\"\n"
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: MyApp
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: AppFeature.SceneDelegate
